### ISSUE TITLE
Billing Address on Payment Page

### ISSUE THREAD

**Issue by OnePhilT** [ctidigital/magento2-google-address-lookup#2]
If I set the following configuration in the Magento admin...

Stores -> Settings -> Configuration -> Sales -> Checkout -> Checkout Options -> Displaying Billing Address On = Payment Page

... the billing address step does not display the address finder. Looking at the module code, I believe it's designed solely to work on the Payment Method, rather than the Payment Page. Is it possible to get this working when the billing address is set to display on the Payment Page? I can try amending the code, but I'm afraid back-end isn't my strong suit!

**Comment by oviliz** [comment]
@OnePhilT , what Magento version are you on?

**Comment by OnePhilT** [comment]
Sorry for delayed response. This was either an issue with the theme, or the Magestore_OneStepCheckout module.
