### ISSUE TITLE
how to send complete address from google finder to street field

### ISSUE THREAD

**Issue by sanganagouda1** [ctidigital/magento2-google-address-lookup#9]
hi i want send that complete address from google street finder to street fields in checkout why because i need complete address to find distance from "warehouse " to "address".so please do the needful

**Comment by bartoszherba** [comment]
What you are looking for @sanganagouda1 is https://github.com/bartoszherba/magento2-google-address-lookup/blob/master/view/src/frontend/web/js/model/address/addressData.js

All you have to do is to require addressData model in your custom script and get appropriate data. Putting everything in one field, serialized or whatever is bad approach.

Here is a sample code:
`
require([''GoogleAddressLookup/model/address/addressData'], function(addressData) {
    const form = addressData.getForm('shippingAddress');
    // Address is a KO observable
    address = form.address();
   // process your logic
}
`

**Comment by sanganagouda1** [comment]
yeah just i want to send "street address" and  locality to street field because, based on that street field i am calculating "Distance " from distance google api so i need street and locality But, as of now its taking only street address means first param ,how to get first 2 params???
LIke:  now in address finder text : 
"Tavarekere Main Road, Cashier Layout, 1st Stage, BTM Layout, Bengaluru, Karnataka, India"

In street field it will take : "Tavarekere Main Road."
so i want to send street with locality  like: "Tavarekere Main Road, Cashier Layout, 1st Stage, BTM Layout,"

**Comment by bartoszherba** [comment]
In js/model/google/strategy/default.js there is encapsulated strategy for filling up the data. If I remember correctly, "place" should have all google response data.
Strategy is used in frontend/web/js/model/google/initializer.js and injected in js/form/dashboard/autocomplete.js
Therefore you should write your custom strategy class to handle your logic and inject it in autocomplete.js

**Comment by sanganagouda1** [comment]
ok thank you

**Comment by sanganagouda1** [comment]
i tried lot to set google finder address to street address ..

**Comment by bartoszherba** [comment]
You know, I gave you all tips I could, you are the developer in the end, I can't work for you ;]
